### ISSUE TITLE
ExtensionValidator.getExtension is incorrect if filename includes extra period characters.

### ISSUE THREAD

**Issue by rick-boardontrack** [sashirestela/slimvalidator#15]
Windows, Linux and Mac all allow filenames like  foo.bar.txt

The getExtension method will return 'bar' instead of 'txt'.

**Comment by rick-boardontrack** [comment]
I've submitted a pull request with a fix along with additional tests.

**Comment by sashirestela** [comment]
@rick-boardontrack Thanks for detecting this issue. Let me take a look.
